### ISSUE TITLE
reference new home of ED on harvard ED page

### ISSUE THREAD

**Issue by badgley** [EDmodel/ED2.mixup#6]
It might be worth updating the information about where to find ED on the harvard page: 
http://www.oeb.harvard.edu/faculty/moorcroft/code_and_data/index.html

I only got here after being unable to access the ED wiki -- which seems to have also moved here.

**Comment by mdietze** [comment]
Grayson,

1) Harvard will still host the major.minor version numbered releases for versions of the code that have been more thoroughly tested. Github is hosting the "development" version of the code. I'm CCing Paul on this so that he knows there's been a request to put a link to the development version as well -- I agree that would be nice but I don't control that webpage

2) Yes, I moved the ED wiki here, both to ensure "one stop shopping" and because the old wiki server was on it's last legs. I thought I had caught all the links to the old wiki from the webpages my lab runs -- could you let me know where you were trying to access the ED wiki from so that I fit it and point other users to the wiki on github?

Thanks for the feedback,

 -- Mike Dietze

**Comment by badgley** [comment]
The README_1ST.pdf at the harvard site points you to: http://128.197.34.149/wiki/index.php/ED2_Documentation

Hasn't responded in the past two days -- though I feel like a month or so ago it was definitely around.

**Comment by mdietze** [comment]
Thanks. I've let Paul know about this too. Unfortunately I have no control over the Harvard server.
